### ISSUE TITLE
Error using default models/aom3

### ISSUE THREAD

**Issue by debasmitdas** [kousw/experimental-consistory#2]
Is using the default models/aom3 working ? I get the following error:

```
Repository Not Found for url: https://huggingface.co/models/aom3/resolve/main/scheduler/scheduler_config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_consistory.py", line 606, in <module>
    pre_generate_images_for_dift(args)
  File "inference_consistory.py", line 62, in pre_generate_images_for_dift
    noise_scheduler = DDPMScheduler.from_pretrained(args.model_name_or_path, subfolder="scheduler", cache_dir = CACHE_DIR)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/schedulers/scheduling_utils.py", line 140, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 385, in load_config
    raise EnvironmentError(
OSError: models/aom3 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.
```
Could you kindly help me out ?

**Comment by kousw** [comment]
You must first download the base model under local ./models folder.
aom3 is what I used for validation, so please rewrite it to what you will use.

If you use models/aom3, it may be the case that it goes to the hugging face to get the model.
Maybe you could use . /models/aom3 might be a better description.

**Comment by debasmitdas** [comment]
Ah ! Thanks for the response. Replacing models/aom3 with hogiahien/aom3 seem to be working. :)
